# Site
name: "Joel Clark"
title: "Digital Portfolio"
description: "iOS developer"
logo: 'assets/images/icon.png'
favicon: 'assets/images/icon.png'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Joel:
    name: Joel
    display_name: Joel
    email: joelhenryclark@gmail.com
    twitter: https://twitter.com/joelhc_dev
    description: "Self-taught iOS developer with a passion for creative software"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

remote_theme: wowthemesnet/mediumish-theme-jekyll
